apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app: yarienici
  name: yarienici-app
spec:
  project: yarienici-project
  source:
    repoURL: https://github.com/Amandine-crdn/yarienici.git
    targetRevision: main
    path: app
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: false
      selfHeal: true