# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "master" do |master|
    master.vm.box = "bento/debian-12"
    master.vm.hostname = "acerdanS"
    master.vm.provider "virtualbox" do |vb|
      vb.cpus = "2"
      vb.memory = "2048"
    end
    master.vm.network "private_network", ip: "192.168.56.110"
    master.vm.provision "shell", privileged: true, path: "scripts/master.sh"
  end
end
