# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "master" do |master|
    master.vm.box = "bento/debian-12"
    master.vm.hostname = "acerdanS"
    master.vm.provider "virtualbox" do |vb|
      vb.cpus = "1"
      vb.memory = "1024"
    end
    master.vm.network "private_network", ip: "192.168.56.110"
    master.vm.provision "file", source: "~/.ssh/id_ed25519.pub", destination: "/tmp/id_ed25519.pub"
    master.vm.provision "file", source: "~/.ssh/id_ed25519", destination: "/tmp/id_ed25519"
    master.vm.provision "shell", privileged: true, path: "scripts/master.sh"
  end

  config.vm.define "slave" do |slave|
    slave.vm.box = "bento/debian-12"
    slave.vm.hostname = "acerdanSW"
    slave.vm.provider "virtualbox" do |vb|
      vb.cpus = "1"
      vb.memory = "1024"
    end
    slave.vm.network "private_network", ip: "192.168.56.111"
    slave.vm.provision "file", source: "~/.ssh/id_ed25519.pub", destination: "/tmp/id_ed25519.pub"
    slave.vm.provision "file", source: "~/.ssh/id_ed25519", destination: "/tmp/id_ed25519"
    slave.vm.provision "shell", privileged: true, path: "scripts/slave.sh"
  end
end
