# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "vm1" do |vm1|
    vm1.vm.box = "bento/debian-12"
    vm1.vm.hostname = "acerdanS"
    vm1.vm.provider "virtualbox" do |vb|
      vb.cpus = "1"
      vb.memory = "1024"
    end
    vm1.vm.network "private_network", ip: "192.168.56.110"
    vm1.vm.provision "file", source: "~/.ssh/id_ed25519.pub", destination: "/tmp/id_ed25519.pub"
    vm1.vm.provision "file", source: "~/.ssh/id_ed25519", destination: "/tmp/id_ed25519"
    vm1.vm.provision "shell", privileged: true, path: "scripts/vm1.sh"
  end

  config.vm.define "vm2" do |vm2|
    vm2.vm.box = "bento/debian-12"
    vm2.vm.hostname = "acerdanSW"
    vm2.vm.provider "virtualbox" do |vb|
      vb.cpus = "1"
      vb.memory = "1024"
    end
    vm2.vm.network "private_network", ip: "192.168.56.111"
    vm2.vm.provision "file", source: "~/.ssh/id_ed25519.pub", destination: "/tmp/id_ed25519.pub"
    vm2.vm.provision "file", source: "~/.ssh/id_ed25519", destination: "/tmp/id_ed25519"
    vm2.vm.provision "shell", privileged: true, path: "scripts/vm2.sh"
  end
end
